# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170905_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=150, unique=True),
        ),
    ]
